### ISSUE TITLE
Create new content type for "People" pages

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-customizations#1]
Dan has created a mockup design for the way this content type should look. Please attach that here.

**Comment by hiesterd** [comment]
# Mayor
![person-mayor](https://cloud.githubusercontent.com/assets/10146145/10309727/221dad36-6c0c-11e5-8cdb-4fba2ce1ddcc.png)
# Council Rep
![person-councilrep-1d](https://cloud.githubusercontent.com/assets/10146145/10309728/22212204-6c0c-11e5-8633-5d8252074cb6.png)
## Council Rep with grid visible
![person-councilrep-withgrid](https://cloud.githubusercontent.com/assets/10146145/10309801/8f43d84a-6c0c-11e5-9c85-b5de82ba63f3.png)

**Comment by inghamn** [comment]
We now have a Person content type
