### ISSUE TITLE
Breadcrumbs in the wrong order

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-customizations#12]
Currently, if there is a sub-topic, that item shows up first in the breadcrumb list. For example:
https://bloomington.in.gov/alpha/health/aging

There should be a separator between breadcrumb items, e.g. ">"

The last item in the breadcrumb (current page) should not be a link

The urls for each item in the breadcrumb should use the term alias, if one has been specified.

**Comment by charlesbrandt** [comment]
This is almost there. This is still an open issue:
The urls for each item in the breadcrumb should use the term alias, if one has been specified.

**Comment by charlesbrandt** [comment]
For example, on this page:
https://bloomington.in.gov/alpha/farmers-market
Clicking "Arts and Culture" does not work.

**Comment by hiesterd** [comment]
Looks like Drupal's `l()` function doesn't work with Taxonomy Terms the same way it does with Nodes. I've done a little digging, and [this documentation page](https://api.drupal.org/api/drupal/modules%21taxonomy%21taxonomy.module/function/taxonomy_term_path/6) looks like it has a promising solution. I'll send you an update after I give this a spin.

**Comment by inghamn** [comment]
Oh yeah, looks like Drupal expects (taxonomy/term/53)


Cliff Ingham
Web Developer
City of Bloomington, Indiana

https://github.com/City-of-Bloomington
https://openhub.net/accounts/inghamn
