### ISSUE TITLE
Directory listings for nested departments

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-customizations#15]
In our directory application, departments are nested inside of other departments.  While the possible depth of department levels is unlimited, our city really only goes down to about three levels of nesting.

The drupal directory integration is only displaying peoples' contact information from the specific department level requested by drupal.  We want to include all the people in sub-departments as well.  

It is an open question whether we want to display the names of the sub-departments recursively.  We may just want ot list all people records in and below the department shown.

**Comment by inghamn** [comment]
We talked about it and decided to show a flat listing of all peoples' contact information within the parent departments.  Additionally, we'll list, in the side panel, all the sub-departments and their contact information.

We won't try to correlate people with the subdepartment.  So, for instance, the Fire department

* list all people (irrespective of what station) on the right-hand side
* list all the stations (the sub-departments) in the sidebar on the left.

**Comment by inghamn** [comment]
We still need to clean up the HTML templating for this listing

**Comment by hiesterd** [comment]
There is some inconsistency in display between dev and production. The display on dev is what I had intended:

![screen shot 2016-04-22 at 11 49 30 am](https://cloud.githubusercontent.com/assets/10146145/14747326/94ae7120-0881-11e6-9775-4688e797b05c.png)

On production, the department information seems to be getting rendered by the function that renders contact information for divisions:

![screen shot 2016-04-22 at 11 54 53 am](https://cloud.githubusercontent.com/assets/10146145/14747352/bc3103d4-0881-11e6-93dd-0e8dc0ab5970.png)
