### ISSUE TITLE
Node revisions cannot be viewed

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-customizations#27]
When looking at the node revisions page in Drupal, clicking on one of the times yields:

The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Drupal\Component\Plugin\Exception\ContextException</em>: Required contexts without a value: node. in <em class="placeholder">Drupal\Core\Plugin\Context\ContextHandler-&gt;applyContextMapping()</em> (line <em class="placeholder">96</em> of <em class="placeholder">core/lib/Drupal/Core/Plugin/Context/ContextHandler.php</em>).

For example:
https://bloomington.in.gov/node/110/revisions/12401/view

**Comment by inghamn** [comment]
The way we're declaring cache contexts for blocks in our custom modules is tripping over this bug.  Trying to view a revision happens over a different route, and our declared cache context is only for the node view.  This means, as written, our block does not have a cache context for the node.

Drupal is supposed to not crash when this happens.  It's supposed to execute the block with no caching.  However, there are bugs that have been outstanding for years on this topic.

https://www.drupal.org/project/drupal/issues/2620126
https://www.drupal.org/project/drupal/issues/2677162

All this means that our custom modules' blocks must be very careful about cache context declarations.  They must:
* declare a cache context of "route"
* declare the context as not required
* check if a node is in the context before doing anything

**Comment by inghamn** [comment]
Revisions are now viewable
